blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/Jacques2Marais/datasleuth/discussions
    about: Please ask and answer questions here
  - name: Documentation
    url: https://github.com/Jacques2Marais/datasleuth#readme
    about: Check the documentation before reporting issues
  - name: Security Issues
    url: https://github.com/Jacques2Marais/datasleuth/security/policy
    about: Please report security vulnerabilities directly to the maintainers
